alias pmv='/home/rosalina/Documents/App/mgltools/bin/pmv'
alias adt='/home/rosalina/Documents/App/mgltools/bin/adt'
alias vision='/home/rosalina/Documents/App/mgltools/bin/vision'
alias cadd='/home/rosalina/Documents/App/mgltools/bin/cadd'
alias pythonsh='/home/rosalina/Documents/App/mgltools/bin/pythonsh'
