"""empty message

Revision ID: 5a7fdc4f3ec6
Revises: 
Create Date: 2019-08-05 18:22:05.404872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7fdc4f3ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PDB_ID', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_PDBfilename', sa.String(), nullable=True),
    sa.Column('original_PDBfilename_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experimental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('resolution', sa.Integer(), nullable=True),
    sa.Column('rfree', sa.Integer(), nullable=True),
    sa.Column('rwork', sa.Integer(), nullable=True),
    sa.Column('main_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_profile_id'], ['protein_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligand_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ligand_id', sa.String(), nullable=True),
    sa.Column('ligand_name', sa.String(), nullable=True),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('inchl_key', sa.String(), nullable=True),
    sa.Column('ligand_PDBfile', sa.String(), nullable=True),
    sa.Column('ligand_PDBfile_url', sa.String(), nullable=True),
    sa.Column('main_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_profile_id'], ['protein_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniprot_id', sa.String(), nullable=True),
    sa.Column('protein_name', sa.String(), nullable=True),
    sa.Column('gene', sa.String(), nullable=True),
    sa.Column('organism', sa.String(), nullable=True),
    sa.Column('protein_PDBfile', sa.String(), nullable=True),
    sa.Column('protein_PDBfile_url', sa.String(), nullable=True),
    sa.Column('main_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_profile_id'], ['protein_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protein_information')
    op.drop_table('ligand_information')
    op.drop_table('experimental_data')
    op.drop_table('protein_profile')
    # ### end Alembic commands ###
